### ISSUE TITLE
Out-of-bounds Read

### ISSUE THREAD

**Issue by saethlin** [RoDmitry/atoi_simd#1]
This bounds check is wrong:
https://github.com/RoDmitry/atoi_simd/blob/293e4e89021959c2f42e97d496e3b8c24b8c0611/src/fallback.rs#L145

It should be
```rust
 let mut val: u64 = unsafe { read_unaligned(s.get_safe_unchecked(8..16).as_ptr().cast()) }; 
```

Applying this change causes a number of tests to fail.

This issue can also be observed using Miri, if I run `cargo +nightly miri test` without the `.cargo/config` in this repo, I can get at least these two UB reports:
```
196 |             let val: u64 = unsafe { read_unaligned(s.get_safe_unchecked(8..).as_ptr().cast()) };
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ using uninitialized data, but this operation requires initialized memory
    |
```
```
   --> src/fallback.rs:145:41
    |
145 |             let mut val: u64 = unsafe { read_unaligned(s.get_safe_unchecked(8..).as_ptr().cast()) };
    |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ memory access failed: alloc29045 has size 9, so pointer to 8 bytes starting at offset 8 is out-of-bounds
```

**Comment by RoDmitry** [comment]
Hi. It should not be 8..16. There is no problem with getting slice of `s`. You might not understand the concept of how this works.
For example we have code:
```rust
let s = "123";
let val: u64 = unsafe { read_unaligned(s.as_ptr().cast()) };
```
`val` at that point might be something like 0xAF3534_333231, that's why it warns us that it might be UB, because it has read extra memory, that we don't own, but on the next line we have:
```rust
let len = check_8(val).min(s.len());
```
which makes sure we have the correct `len` of our data.

**Comment by saethlin** [comment]
```rust
let s = "123";
let val: u64 = unsafe { read_unaligned(s.as_ptr().cast()) };
```
This program is UB. It contains a buffer overflow.

**Comment by Shnatsel** [comment]
To elaborate on what @saethlin said: it does not matter if data read from out of bounds is never used; the very act of reading from out of bounds is already a problem.

Languages like C or Rust define what is legal and illegal to do within them. Reading out of bounds is always illegal, and since it is illegal, the compiler assumes it will never happen. Such illegal operations are (somewhat confusingly) called "undefined behavior"; you can learn more about the concept [here](https://www.ralfj.de/blog/2021/11/18/ub-good-idea.html). In C and Rust any operation that reads out of bounds is undefined behavior, and should never be performed. Programs that read out of bounds are a typical cause of security vulnerabilities; they are #7 on the CWE [list](https://cwe.mitre.org/data/definitions/1425.html) of most dangerous software vulnerabilities.

An out-of-bounds read would be legal in assembly, if and only if you also took precautions to never cross the page boundary, but using an unaligned read makes it illegal even in pure assembly.

That is to say, this is a genuine problem that needs to be fixed.

**Comment by RoDmitry** [comment]
I have read about it, and I still don't understand why it is illegal. The only thing I have found is that it has access to that extra memory, but it does not write there, just reads and then drops it. @Shnatsel, you definitely has more experience than me about it. Can you give me examples of what bad can happen, and how dangerous it can be?

**Comment by Shnatsel** [comment]
The best case for your current code is that it is lowered into assembly exactly as written, but when the buffer happens to be near the page boundary so that your read crosses it, your program is killed by the OS due to the illegal memory access.

The worst-case scenario for an out-of-bounds read is this: https://en.wikipedia.org/wiki/Heartbleed

Once you have performed an operation that the language explicitly specifies must never be performed, literally anything can happen. It may work for some inputs but not others; or it may work on some compiler version or not others, or with certain compiler flags or not others, or allow an attacker that provides a carefully crafted string for your code to parse execute arbitrary code on your computer. Absolutely anything can happen because you have broken the basic rules of reality.

**Comment by Shnatsel** [comment]
Perhaps a more accessible explanation of undefined behavior can be found here: https://www.ralfj.de/blog/2019/07/14/uninit.html

`atoi_simd` also performs reads from uninitialized memory, so this is going to be relevant here as well.

**Comment by RoDmitry** [comment]
I think about cloning data in an Array with bigger capacity, then the bounds will be right. But I think the speed will be worse. Have to benchmark it.

**Comment by Shnatsel** [comment]
[u64::from_ne_bytes](https://doc.rust-lang.org/stable/std/primitive.f64.html#method.from_ne_bytes) lowers into a load. Here is proof on godbolt: https://godbolt.org/z/a5GPfs61s The function is just a bounds check and a load. (I have written a [very detailed article](https://shnatsel.medium.com/how-to-avoid-bounds-checks-in-rust-without-unsafe-f65e618b4c1e) on avoiding bounds checks that also covers inspecting the generated assembly, it might come in handy). However, `u64::from_ne_bytes` requires the input slice to be 8 bytes in length.

There is no way to read from a variable-length slice that may be under 8 bytes in length to a u64 efficiently and without UB. This is why when the compiler processes a slice in a loop with SIMD instructions, it has to insert special handling of the end that may be shorter than SIMD allows, where it reads byte-by-byte.

> I think about cloning the data in an Array with bigger capacity, then the bounds will be right. But I think the speed will be worse. Have to benchmark it.

If you do this on a variable-length input, it will lower to a `memcpy()` call: https://godbolt.org/z/1P5hbr6jP

`memcpy()` is usually optimized for large inputs and will not be great for this use case. You could try writing a manual loop that copies byte-by-byte and see if that helps at all; I don't know if it will, but at least it's worth a shot.

**Comment by RoDmitry** [comment]
Is [this](https://github.com/RoDmitry/atoi_simd/blob/293e4e89021959c2f42e97d496e3b8c24b8c0611/src/simd_sse_avx.rs#L27) also UB for `s = b"123"`?

**Comment by Shnatsel** [comment]
Yes. `b"123"` is 3 bytes (24 bits) long, while the SIMD load performs a 16-byte (128-bit) load and goes out of bounds. The [original blog post](https://rust-malaysia.github.io/code/2020/07/11/faster-integer-parsing.html) gets away with this only because in their case the input is always 16 characters long.

You could still make use of SIMD if you pad the input with zeroes up to 16 characters, turning `b"123"` into `b"000000000123"`. You can achieve this by making a `[b'0'; 16]` and copying the actual input to the end, but the copy still has to be done byte-by-byte. However, a 16 characters long buffer is not going to be enough for many numeric types. For example, the maximum value representable by a `u64` is [18446744073709551615](https://doc.rust-lang.org/stable/std/primitive.u64.html#associatedconstant.MAX) which is 21 characters long. And `u128` maximum value is 40 characters long. So you might have to use bigger buffers than 16 if you want to keep using SIMD.

**Comment by RoDmitry** [comment]
For the record, at some point, [I did use an array](https://github.com/RoDmitry/atoi_simd/blob/c11286050c4533fe9184d66c3fa63cc4a7c2ed0d/src/lib.rs#L49), and it was slower. Will test it again

**Comment by RoDmitry** [comment]
I have made separate functions `read_8` and `read_16`, and have tested this:
```rust
fn read_8(s: &[u8]) -> u64 {
    let mut buf = [0u8; 8];
    let len = s.len().min(8);
    buf[..len].copy_from_slice(&s[..len]);
    u64::from_ne_bytes(buf)
}
```
And also this:
```rust
fn read_8(s: &[u8]) -> u64 {
    if s.len() < 8 {
        let mut buf = [0u8; 8];
        buf[..s.len()].copy_from_slice(s);

        return u64::from_ne_bytes(buf);
    }

    unsafe { read_unaligned(s.as_ptr().cast()) }
}
```
It's more than 2x slower. (In case anybody wants, you can test it with `cargo bench -- "parse u64/9"`, without the `.cargo/config`)
And Miri is happy now, but not me..

**Comment by Shnatsel** [comment]
I agree that this performance degradation is frustrating.

You might want to check if a manual loop is faster than a `copy_from_slice` which is a `memcpy()` behind the scenes. `memcpy()` is usually optimized for big copies, not small ones, so a manual loop over a number of elements known to be small might be faster.

**Comment by RoDmitry** [comment]
You are right. This:
```rust
fn read_8(s: &[u8]) -> u64 {
    if s.len() < 8 {
        let mut buf = [0u8; 8];
        for (i, ch) in s.into_iter().enumerate() {
            buf[i] = *ch;
        }

        return u64::from_ne_bytes(buf);
    }

    unsafe { read_unaligned(s.as_ptr().cast()) }
}
```
is faster than previous. But resulting assembly somehow looks like shit) And yet it's faster. I did not know that `memcpy()` is that slow for small datasets.

**Comment by Shnatsel** [comment]
These two variants are also worth benchmarking:

```rust
fn read_8(s: &[u8]) -> u64 {
    if s.len() < 8 {
        let mut buf = [0u8; 8];
        for (b, ch) in buf.iter_mut().zip(s.into_iter()) {
            *b = *ch;
        }

        return u64::from_ne_bytes(buf);
    }

    unsafe { read_unaligned(s.as_ptr().cast()) }
}
```
(although you don't even need this `unsafe` because `u64::from_ne_bytes(s[..8])` should produce the same assembly)

and 

```rust

fn read_8(s: &[u8]) -> u64 {
    let mut buf = [0u8; 8];
    for (b, ch) in buf.iter_mut().zip(s.into_iter()) {
        *b = *ch;
    }

    return u64::from_ne_bytes(buf);
    }
}
```

**Comment by RoDmitry** [comment]
First is as slow as `copy_from_slice`.
Without unsafe is even slower.

**Comment by Shnatsel** [comment]
That makes me suspect something is wrong with the benchmarking setup, because the safe and unsafe variant literally produce the exact same assembly.

Unsafe: https://godbolt.org/z/M4h5bT476
Safe: https://godbolt.org/z/cK6zWfvK4

**Comment by Shnatsel** [comment]
For a start, make sure you use [`std::hint::black_box`](https://doc.rust-lang.org/stable/std/ptr/fn.read_unaligned.html) on both the input and output in your benchmarking harness, and that the results are consistent between benchmarking runs.

**Comment by RoDmitry** [comment]
Maybe I misunderstood you. Second time I ran this:
```rust
fn read_8(s: &[u8]) -> u64 {
    let mut buf = [0u8; 8];
    for (b, ch) in buf.iter_mut().zip(s.into_iter()) {
        *b = *ch;
    }
    u64::from_ne_bytes(buf)
}
```

**Comment by Shnatsel** [comment]
Ah, I see. I thought you applied my suggestion to get rid of unsafe, and that slowed it down. 

In that case the fastest option is this: https://godbolt.org/z/cK6zWfvK4

Although the recommendation to use `black_box` in benchmarks on both the input and output still stands. Otherwise the measurements may not be representative of the real world performance due to the compiler precomputing some of the results.

**Comment by RoDmitry** [comment]
You can see my benchmarks [here](https://github.com/RoDmitry/atoi_simd/blob/master/benches/benchmark.rs). As far as I understood, Criterion does not need extra `black_box`.
For the `u64::from_ne_bytes(s[..8].try_into().unwrap())`, yes it's the same speed, but crate edition is 2018, and this edition does not support `try_into`. If it has same assembly, then there is no difference, as I understand.

**Comment by Shnatsel** [comment]
It supports it full well, you just have to import it. Just `use std::convert::TryInto` and it works.

**Comment by RoDmitry** [comment]
Right, my bad

**Comment by Shnatsel** [comment]
Criterion does not black-box inputs or outputs automatically (even though it arguably should, that would be much more intuitive). 

Proof: https://docs.rs/criterion/latest/src/criterion/benchmark_group.rs.html#259-271 - no mention of black_box anywhere in the file.

In general you have to black_box both the input and output of the operation you are measuring for the measurement to be representative of real-world workloads. But maybe you got (un)lucky this time and the compiler did not constant-fold much.

**Comment by RoDmitry** [comment]
It does: [link](https://github.com/bheisler/criterion.rs/blob/180f4b48964a1fe6bdd7c49cf6d197071bee2e9b/src/bencher.rs#L88)

**Comment by Shnatsel** [comment]
Ah, I stand corrected! That's great news. 

Although it only does it for the outputs, not for inputs. Perhaps I should make a PR for that, but that's outside the scope of this issue.

**Comment by Shnatsel** [comment]
Hmm, actually, I don't think the inputs can be automatically black-boxed with that API, so that still has to be done manually. But that is off-topic for this issue, we can make a new one if this needs to be discussed further.

**Comment by RoDmitry** [comment]
The input is passed with `.bench_with_input()`. It must be doing something, if it's there)

**Comment by Shnatsel** [comment]
@orlp came up with this, it should be quite fast at reading a u64 without undefined behavior:

```rust
pub fn load_padded_le_u64(bytes: &[u8]) -> u64 {
    let len = bytes.len();
    if len >= 8 {
        return u64::from_le_bytes(bytes[0..8].try_into().unwrap());
    }
    
    if len >= 4 {
        let lo = u32::from_le_bytes(bytes[0..4].try_into().unwrap());
        let hi = u32::from_le_bytes(bytes[len-4..len].try_into().unwrap());
        return (lo as u64) | ((hi as u64) << 8*(len - 4));
    }
    
    if len == 0 {
        return 0;
    }
    
    let lo = bytes[0] as u64;
    let mid = (bytes[len/2] as u64) << 8 * (len / 2);
    let hi = (bytes[len - 1] as u64) << 8 * (len - 1);
    lo | mid | hi
}
```

**Comment by RoDmitry** [comment]
Did you test it? It does not work

**Comment by orlp** [comment]
@RoDmitry Can you give an example input for which it is incorrect? I did test it with random data but perhaps I overlooked something.

**Comment by RoDmitry** [comment]
My mistake. It works good.

Meanwhile I did this:
```rust
fn read_8(s: &[u8]) -> u64 {
    if s.len() < 8 {
        let mut val = 0;
        for ch in s.into_iter().rev() {
            val = (val << 8) | *ch as u64;
        }

        return val;
    }
    u64::from_ne_bytes(s[..8].try_into().unwrap())
}
```
which is slower than yours)

**Comment by RoDmitry** [comment]
Is `/ 2` (dividing by 2) optimized to the same speed as `>> 1`?

**Comment by Shnatsel** [comment]
@RoDmitry please let me know once all the miri issues are fixed and you are satisfied with the performance of the implementations that do not trigger undefined behavior.

Once that's done, I'll perform additional verification of memory safety and correctness using a fuzzer.

**Comment by RoDmitry** [comment]
Will do, thanks!)

**Comment by RoDmitry** [comment]
Fixed out-of-bounds read for Fallback with b27bf23698b78f6d6efe01176695eaaf40cb463a

**Comment by Shnatsel** [comment]
Nice!

miri currently cannot handle SIMD, but Address Sanitizer detects an out-of-bounds read in SIMD code still.

**Comment by RoDmitry** [comment]
@orlp any ideas optimizing these two functions?
```rust
pub fn read_16(s: &[u8]) -> u128 {
    let len = s.len();
    if len >= 16 {
        return u128::from_le_bytes(s[0..16].try_into().unwrap());
    }

    if len >= 8 { // 12?
        let lo = u64::from_le_bytes(s[0..8].try_into().unwrap());
        let hi = u64::from_le_bytes(s[len - 8..len].try_into().unwrap());

        return ((hi as u128) << (8 * (len - 8))) | (lo as u128);
    }

    /* if len >= 8 {
        let lo = u64::from_le_bytes(s[0..8].try_into().unwrap());
        let hi = u32::from_le_bytes(s[len - 4..len].try_into().unwrap());

        return ((hi as u128) << 8 * (len - 4)) | (lo as u128);
    } */

    if len >= 4 {
        let lo = u32::from_le_bytes(s[0..4].try_into().unwrap());
        let hi = u32::from_le_bytes(s[len - 4..len].try_into().unwrap());

        return (((hi as u64) << (8 * (len - 4))) | (lo as u64)) as u128;
    }

    if len == 0 {
        return 0;
    }

    let lo = s[0] as u64;
    let mid = (s[len >> 1] as u64) << (8 * (len >> 1));
    let hi = (s[len - 1] as u64) << (8 * (len - 1));
    (lo | mid | hi) as u128
}

pub fn read_32(s: &[u8]) -> [u128; 2] {
    if s.len() > 16 {
        return [
            u128::from_le_bytes(s[0..16].try_into().unwrap()),
            read_16(&s[16..]),
        ];
    }

    [read_16(s), 0]
}
```
I am trying to use it in SIMD, but it's like 3-5x slower than `core::mem::transmute_copy(&s)`
I use it like that:
```rust
unsafe fn read(s: &[u8]) -> __m128i {
    // _mm_loadu_si128(core::mem::transmute_copy(&s))
    _mm_loadu_si128(&read_16(s) as *const u128 as *const __m128i)
}

#[inline(always)]
unsafe fn read_avx(s: &[u8]) -> __m256i {
    // _mm256_loadu_si256(core::mem::transmute_copy(&s))
    _mm256_loadu_si256(&read_32(s) as *const [u128; 2] as *const __m256i)
}
```

**Comment by orlp** [comment]
@RoDmitry `u128` stuff can be pretty slow. I'm sorry I can't help much here right now, it would take too much of my time to look exactly into what you're doing.

**Comment by RoDmitry** [comment]
Never mind, I will try to use SIMD there.

**Comment by RoDmitry** [comment]
@Shnatsel fixed

**Comment by Shnatsel** [comment]
Excellent! I'll give it a whirl with a fuzzer later today. If I don't find anything it'd be great to release the version with the fixes to crates.io.

Would you like me to also file a security advisory so that people using `cargo audit` or Github advisory service got notified about this issue if they use an older version?

**Comment by RoDmitry** [comment]
I still don't consider it as security vulnerability, more like a bug, which can crash your program, but If you think it will be useful, then of course.

**Comment by Shnatsel** [comment]
No more memory safety issues flagged by `cargo fuzz` or `cargo miri test`.

Let's ship it!
